### ISSUE TITLE
NPE on instant run on login screen

### ISSUE THREAD

**Issue by yogurtearl** [googlesamples/android-topeka#61]
Using  1d973e8 :

Upgrade plugin to 2.0.0-alpha1+

Launch topeka, edit first_name string resource, then hit "instant run":

App will crash with:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.samples.apps.topeka.model.Avatar.ordinal()' on a null object reference
at com.google.samples.apps.topeka.fragment.SignInFragment.onSaveInstanceState(SignInFragment.java:96)
at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2109)
at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:1767)
at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1835)
at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:125)
at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:523)
at android.app.Activity.performSaveInstanceState(Activity.java:1298)
at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1289)
at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4088)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4050)
at android.app.ActivityThread.-wrap15(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616

```

**Comment by keyboardsurfer** [comment]
Fixed in #59.

**Comment by ardock** [comment]
@keyboardsurfer Reopen this issue please, it's not fixed.

After the default avatar was removed, I fixed the simple case when no avatar is selected but not when you recreate the activity and restore it from the saved state. You only need to rotate the device to reproduce this one.

I fixed this one already but I didn't update my PR because I found another related to use `GridView.getChildAt`, another NPE, my idea was to fix all today. I'll offer one possible solution later.
